### ISSUE TITLE
No server admin password

### ISSUE THREAD

**Issue by SoberAddiction** [Acekorneya/Ark-Survival-Ascended-Server#10]
Line 126 in launch_ASA.sh has the admin password string in it. It should be moved to just before the BattleEye argument so that the server admin password actually works.
Check out this quick example:
https://www.youtube.com/watch?v=dN8gGi4qyIU

**Comment by Acekorneya** [comment]
Server Admin Does work they way i have if you check the GameUserSetting.ini File you can see it does put whatever you put on the docker-compose.yaml file i have there as i 've tested my Self and that how i was able to get it to work

**Comment by SoberAddiction** [comment]
My install must be special then, because I can't get admin commands to work for the life of me.

**Comment by Acekorneya** [comment]
> My install must be special then, because I can't get admin commands to work for the life of me.
> 
> -edit: But seriously, when I set the password, it saves fine until I start the server. then it saves as this: "ServerAdminPassword=-clusterid=cluster"
> 
> If I set it to blank, I still cannot use admin commands. (Not saying that that's on you and not user error.)

What password are you using like any special character or something... the reason why i moved it at the end like that was to avoid that issue as i was having it also so me moving it to the back fixed that issue for me like can you send me you docker-compose.yaml file for testing or give me the password you are using to i can test my self also would be awesome im thinking it could be something with the characters being use but idk until i test it

**Comment by SoberAddiction** [comment]
The update where you added RCON actually fixed it for me. It is now saving properly to my config where it wasn't before. And having RCON took care of what I was wanting. Thank you.
