### ISSUE TITLE
Add -crossplay Environment variable?

### ISSUE THREAD

**Issue by avrignaud** [Acekorneya/Ark-Survival-Ascended-Server#16]
Hi! Hoping to use your Docker solution to run an ARK Survival Ascended dedicated server in Docker (instead of the Windows PC I'm using right now). One issue is that new Xbox or Playstation players can only connect to a dedicated server if the -crossplay argument is added to the server launch command. And weirdly, -crossplay has to be the very last variable, otherwise it doesn't work (no idea why, but it's a known issue). Was wondering if there was any way to add crossplay support to your wonderful solution? Thank you!

**Comment by avrignaud** [comment]
Never mind - found the custom environment variable option. Thanks!

**Comment by avrignaud** [comment]
And I'm back. Having gotten the server up and running, I am having the same problem I had on the windows server. The -crossplay flag seems to only be respected if it's the last argument given. Moving it to the last argument fixed the issue on Windows PC (allowing the server to be discoverable in the "Unofficial" servers tab within the Xbox client), and I'm guessing it would also fix the issue here. Is there any way to try and force this crossplay flag to be the last option given? Or other suggestions? Thank you!

**Comment by Acekorneya** [comment]
In ASA Crossplay is enable by default you don't need to add -Crossplay that was only for ASE
