### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by jerome80** [Acekorneya/Ark-Survival-Ascended-Server#17]
![Capture d'écran 2023-12-13 143404](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/32602783/899ca002-8318-4c79-b1da-73d6810fcbf7)

**Comment by Acekorneya** [comment]
yeah you have to increase you vm.max_map_count like it says in the instruction you can also run this command 
```
sudo -s echo "vm.max_map_count=262144" >> /etc/sysctl.conf && sysctl -p
```
