### ISSUE TITLE
Server not updating.

### ISSUE THREAD

**Issue by devinvb** [Acekorneya/Ark-Survival-Ascended-Server#18]
Hello,

The server doesn't seem to be updating.
I have tried re-pulling the latest docker image and booting it again, but it keeps showing
```
asa_Server  | No update required. Server build ID 12935686 is up to date.
asa_Server  | Server is already running the latest build ID 12935686. Proceeding to start the server.

asa_Server  | [2023.12.13-22.20.44:651][  0]ARK Version: 32.21
asa_Server  | [2023.12.13-22.20.46:443][  7]Primal Game Data Took 0.00 seconds
asa_Server  | No updates.
```

My locally installed steam is showing build ID: 12932517, and the official servers show version 32.23.

The server starts up fine, but I can not find in it the list nor connect via ingame console using `open serverip:7777`

**Comment by StuartWhelan** [comment]
The update for unoffical servers has not been released by the devs/publisher.

**Comment by Acekorneya** [comment]
yeah always check here to see if a new build has been released https://steamdb.info/app/2430930/depots/
