### ISSUE TITLE
After Serverupdate Server not connectable

### ISSUE THREAD

**Issue by gregorsoll** [Acekorneya/Ark-Survival-Ascended-Server#19]
Hi.
Every time after an automatic update, the server will not be listed.
Log's log fine.
I'll then stop and restard the container manually with docker-compose down  / up

Any ideas ?

**Comment by Acekorneya** [comment]
there was an update by the devs and now you have to maker sure you have selected "show player servers" to see your server 
![Screenshot 2023-12-15 084432](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/132539744/1f8dbff1-312f-4f83-8aa1-07a13fe0be6a)
