### ISSUE TITLE
Argument -nosteamclient

### ISSUE THREAD

**Issue by trolldu47** [Acekorneya/Ark-Survival-Ascended-Server#25]
Hello, I want to connect to the ark ascended server except that I don't see my server. I searched for a little while and I ended up noticing that the server starts with the -nosteamclient argument so I guess that's it. Is this what's stopping me from finding my server?  Thanks in advance:

> TheIsland_WP?listen?SessionName="zouzu"?Port=7777?RCONEnabled=True?RCONPort=27020?ServerPassword=test?ServerAdminPassword=MyPassword -WinLiveMaxPlayers=70 -clusterid=cluster -ClusterDirOverride=/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame/Cluster -servergamelog -servergamelogincludetribelogs -ServerRCONOutputTribeLogs -NotifyAdminCommandsInChat 

>  -nosteamclient

>  -NoBattlEye

**Comment by Acekorneya** [comment]
![Screenshot_2023-12-15_084432](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/132539744/2a801ee1-b322-4171-8a41-bed6c78d75ca)

Make Sure you have Selected "Show PLayers Server" to be able to see self hosted servers

**Comment by trolldu47** [comment]
my server is not hosted on my pc I run it on a linux machine separate from my pc

**Comment by Acekorneya** [comment]
Have you check battlemetrics to see if you see your server but make sure you have selected "show player server" to be able to see non nitrado hosted servers

**Comment by trolldu47** [comment]
I don't have this option when I go to multiplayer:
show player serve

**Comment by trolldu47** [comment]
I don't have this option in my menu: "show player server"

**Comment by Acekorneya** [comment]
It should be there make sure your game is updated EVERYONE has that option is on the bottom right

**Comment by trolldu47** [comment]
can we modify the server version to pass to another build
