### ISSUE TITLE
missing "guide" for control

### ISSUE THREAD

**Issue by crckdns** [Acekorneya/Ark-Survival-Ascended-Server#27]
at first: I dislike docker, so I've never learned really using it, even though I'm hosting debian servers for over 10 years.

in the readme I'm really missing a simple example how to start and stop the server or even the container.

internet could not answer me, what the difference is between docker stop asa-server and docker compose stop.
When do I have to use compose -d or what it is called.

For now I used docker stop asa_Server and then docker start asa_Server and this seems to work?
How do I get to the console which was visible after docker compose up in the beginning? I guess there is no way to run it inside of a tmux?

Thanks!

**Comment by Acekorneya** [comment]
Yeah i'll create a better guide.. but mainly if you use the command  docker compose up -d the -d flag will hide all the console output if you want to see what the script is doing just do docker compose up and if you want to bring down the container is docker compose down... docker stop and docker start doesn't bring down the container it just takes it offline you want to do docker compose down command to fully remove the container but we we have volume the data is not lost when fully taking the container down... my other suggestion on learning docker is use chat GPT

**Comment by Acekorneya** [comment]
Here is my new version of the script still testing it but should work and it has way more commands and can handle cluster set up for you etc..  and improver the documentation within the script to help users here are the steps if you want to use it 

**1. Create or Modify User for Container**

- For a new user named `pokuser`:
```bash
sudo useradd -u 1000 -g 1000 -m -s /bin/bash pokuser
```

- To modify an existing user:
```bash
sudo usermod -u 1000 <existing_username>
sudo groupmod -g 1000 <existing_username>
```

**2. Configure System Settings**

- Set `vm.max_map_count` temporarily:
```bash
sudo sysctl -w vm.max_map_count=262144
```

- For permanent setup, add `vm.max_map_count=262144` to `/etc/sysctl.conf`, save, and apply changes:
```bash
sudo sysctl -p
```

**3. Adjust Permissions (Optional)**

- Adjust folder permissions if not using a separate user:
```bash
sudo chown -R 1000:1000 /path/to/your/instance/folder
```

**4. Download & Setup**

- Simplified download and setup command:
```bash
git clone -b beta --single-branch https://github.com/Acekorneya/Ark-Survival-Ascended-Server.git && sudo chown -R 1000:1000 Ark-Survival-Ascended-Server && sudo mv Ark-Survival-Ascended-Server/POK-manager.sh . && sudo chmod +x POK-manager.sh && sudo mv Ark-Survival-Ascended-Server/defaults . && sudo rm -rf Ark-Survival-Ascended-Server
```
This command accomplishes several tasks efficiently:
  - Clones the beta version of the ARK Survival Ascended Server.
  - Changes the ownership of the downloaded files to `pokuser`.
  - Moves the `POK-manager.sh` script to the current directory and makes it executable.
  - Moves the `defaults` directory to the current directory.
  - Cleans up by removing the cloned repository folder.

**5. Run the POK-manager.sh Script**

- To set up and start your ARK server instance:
```bash
./POK-manager.sh -setup
./POK-manager.sh -create <instance_name>
```

**6. View Server Status**

- To view the server status:
```bash
./POK-manager.sh -status -all
```
or for a specific instance:
```bash
./POK-manager.sh -status <instance_name>
```

**All Available Commands**

- To explore all the script's capabilities:
```bash
./POK-manager.sh
```

**Note:** Use `sudo` with `POK-manager.sh` commands if you've set up folder permissions using it.

This guide is designed to streamline your setup process. Please report any feedback or issues you encounter to help us refine the beta script. 

⚠ **Important Notice:** As this is a beta version, please proceed with caution. Though we've addressed many bugs, there may still be unforeseen issues.


⚡ **Additional Note:** The requirement for setting the PUID and PGID can be bypassed by prefixing commands with `sudo`. For example, you can use `sudo ./POK-manager.sh` for operations without needing to adjust the user's UID and GID. This is especially useful for quick tests or when you prefer not to modify user settings.

**Comment by Acekorneya** [comment]
FIx the documentation now https://github.com/Acekorneya/Ark-Survival-Ascended-Server/blob/master/README.md
