### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by Croydon** [Acekorneya/Ark-Survival-Ascended-Server#28]
Please specify the license of the code in this repository. Add a `LICENSE` file to the repository accordingly.

If you don't know much about licenses, have a look at https://choosealicense.com

I would recommend the MIT license: https://choosealicense.com/licenses/mit/

**Comment by Acekorneya** [comment]
Thank you for you feedback i added the MIT License... new to all this but THANK YOU
