### ISSUE TITLE
no server detected

### ISSUE THREAD

**Issue by gamersalpha** [Acekorneya/Ark-Survival-Ascended-Server#32]
Hello so i got this message : 
![image](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/32466950/381ea4fc-a36c-49b8-a74f-7d6c3105e563)

i can't found the serveur, but he is started on docker-compose : 

![image](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/32466950/9560999b-9a18-433e-ba5d-d65080b129d1)

**Comment by Acekorneya** [comment]
you have to go in-game and select "Show Player Server" and then search it and you should find it DONT use steamgui  to find the server is not supported for ASA
