### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by zokradonh** [Acekorneya/Ark-Survival-Ascended-Server#4]
How do you gracefully shut down the server?

`docker compose stop` will SIGTERM the sh process, which will ignore the signal more or less and after 10s docker compose will SIGKILL all processes without saving. This means a rollback of some minutes for the ARK save.

So I suggest adding something like this:
```
_term() { 
  wine taskkill /PID $SERVER_PID
}

# Main function
main() {
    trap _term SIGTERM
```
(untested code) 
I don't know much about wine.
Also I don't know yet if the ASA Server will trigger a world save on `taskkill` command. Hopefully we don't need RCON for this.

`sleep infinity` at the end of main() is also a problem for a graceful shutdown.

I can do a pull request in the next days, when I find some free time, but I'm afraid your whole project structure changed already in that time. xD thank you for all your work and constant updates.

**Comment by Acekorneya** [comment]
Yeah i know that is my next thing on my list is finding a way to do gracefully shutdown by creating a save etc before it shutdown but thank for the code snippet should help me figure it out :)

**Comment by zokradonh** [comment]
this is good to know. Do you already have some findings how to trigger a world save? I had no time for further investigations yet.

**Comment by Acekorneya** [comment]
> time 

As of right now the only way to do it would be to use rcon and if you don't want to use rcon we would have to wait until a save is made then we can proceed with the shutdown that way I can accommodate the people that want to use rcon and the one that don't

**Comment by Acekorneya** [comment]
I've Implement a Graceful Shutdown they only way was to use Rcon to be able to send a save command before we bring down the container
