### ISSUE TITLE
Not all Game.ini & GameUserSettings.ini being observed

### ISSUE THREAD

**Issue by dash74** [Acekorneya/Ark-Survival-Ascended-Server#42]
I have two identical docker environments setup. One using your project and the other using azixus's project. Both of them are using identical Game and GameUserSettings files. However, somehow yours is not observing all of the settings. Specifically related to XP Multiplier, Taming Speed Multiplier, Harvest Multiplier, & BabyCuddleIntervalMultiplier. These are the only ones that I have identfied so far. The first screenshot is your setup and the other is from azixus's. I have attempted to identify how these are not being observed or overridden and are unable to locate the issue. The screenshots were taken from ShowMyAdminManager in-game.

![image](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/28696570/bedf2d92-dfb3-40f5-99df-b2f16669a76e)

![image](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/28696570/efb975fa-1b22-49f9-ab22-d2a3b11bcdcf)

**Comment by S-guchi** [comment]
-UseDynamicConfig?

**Comment by dash74** [comment]
> -UseDynamicConfig?

Well that was a easy fix. I had never used that switch before and since it is in the settings for the initial install. I didn't think much about it. I appreciate the help and now understand what that switch does.
