### ISSUE TITLE
Config files - beacon

### ISSUE THREAD

**Issue by james-barrett** [Acekorneya/Ark-Survival-Ascended-Server#55]
Hi, just a query.

Is there any reason beacon manager would have issues, it basically just writes to the config files but I can't get breeding edits to work, does the container do anything other than pass the files in the config pass through.

Also how does it build the start command? Can I add "text" and - flags to the extra args section without issue?

Mant thanks

**Comment by Acekorneya** [comment]
yeah if you dont want to use official server settings make sure to remove ```-UseDynamicConfig``` from  ```- CUSTOM_SERVER_ARGS=-UseDynamicConfig``` so it should look like this ```- CUSTOM_SERVER_ARGS=``` and you can do `-edit` to remove it from the docker-compose.yaml file

**Comment by james-barrett** [comment]
Great thanks, I saw another post on here that helped me solve it. Love the docker container and POK manger very helpful, even doing a - custom Dino wipe so easy.

Thank you
