### ISSUE TITLE
Auto update fails

### ISSUE THREAD

**Issue by locint** [Acekorneya/Ark-Survival-Ascended-Server#60]
I've been having this issue with the script that auto update is failing. 

SteamCMD says failed to install missing file permissions. 

 I think it has something to do with sudoing the steamcmd command. Everything seems to work fine if I alter the line and remove the sudo but its rather annoying that every time when I update the script is changed back.

Any suggestions?

**Comment by Acekorneya** [comment]
what line exactly are you referring? so i can see that the issue could be thanks for the feedback

**Comment by locint** [comment]
For some reason there was no problem during last night's auto update.  The line was 1585.

**Comment by locint** [comment]
Last night this issue reappeared. 

I am getting error that says server files not found.  Update command claims that everything is up to date.

If I remove ServerFiles folder and try updating again I am getting the SteamCMD permission error.

I think it has something to do with the fact that its trying to access root's logs.

I did not have time to find out a workaround this time.

user@debian-homeserver:~/asadocker$ ./POK-manager.sh -update
Checking for updates to POK-manager.sh...
----- POK-manager.sh is already up to date -----
Using Docker Compose command: 'docker compose' (read from file).
User has chosen to run Docker commands without 'sudo'.
----- Checking for updates to POK-manager.sh -----
POK-manager.sh is already up to date.
----- Checking for updates to Docker image and server files -----
Pulling Docker image: acekorneya/asa_server:2_0_latest
2_0_latest: Pulling from acekorneya/asa_server
Digest: sha256:0bbacd77d049bbc15703c82f0503fcdf6b53827f5d24c7ad5445e843592085b2
Status: Image is up to date for acekorneya/asa_server:2_0_latest
docker.io/acekorneya/asa_server:2_0_latest
SteamCMD is already installed.
---- ARK server files not found. Installing server files using SteamCMD -----
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1721172922
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
ERROR! Failed to install app '2430930' (Missing file permissions)
Failed to install ARK server files using SteamCMD. Please check the logs for more information.

**Comment by locint** [comment]
Got it to update after removing sudo from lines 1585 and 1548 and when it asks for sudo I just press ctrl + c and it continues and installs the files. 

Also the logging directory now points to my home folder instead of root's steam logs.

**Comment by Acekorneya** [comment]
Thank you so much yeah I'll remove the sudo line from the update command.. usually when you stop and start the container again there is an update script that check for update when the container start up so that's another way you can update the game if the update command give you more issues.. but yeah I'll try your fix by removing the sudo command and hopefully that fixes the issue with the update command

**Comment by locint** [comment]
Thank you!

**Comment by Acekorneya** [comment]
i have updated the POK-manager.sh with the new changes hopefully that helps out and Thanks again for the feedback
