### ISSUE TITLE
is it possable. 

### ISSUE THREAD

**Issue by Ky1duck** [Acekorneya/Ark-Survival-Ascended-Server#63]
I am wanting to try and run my servers on linux and this looks like a good fit for me, but 1 question i have is it possable to move my current windows server saves over to this on as none of my players want to start over. also how well dose this support clusters?

Thanks ahead of time.

**Comment by Acekorneya** [comment]
You just need to move your save folder into `/Instance_name_of_instance/Saved/SavedArks/Instance_PVE_Aberration/Saved/SavedArks` and make sure all files have a UID and GID of 1000 for permissions. Your save should then transfer. It also works for clustering: just create another instance, change the `ASA_PORT` and `RCON_PORT` on the second instance, and it should start up. As long as port forwarding is correct, it should work.
