### ISSUE TITLE
NotifyAdminCommandsInChat

### ISSUE THREAD

**Issue by inferno771** [Acekorneya/Ark-Survival-Ascended-Server#66]
I was wondering if its possible to have the "-NotifyAdminCommandsInChat" passed to the server on startup as an optional toggle and not always on?

Thanks in advance!

**Comment by Acekorneya** [comment]
Yeah i can try to find a way to make it a toggle option maybe i'll just add it to the docker-compose.yaml file

**Comment by Acekorneya** [comment]
Thank you for your suggestion! We've implemented the ability to toggle the `"-NotifyAdminCommandsInChat" `option. This feature is now available in the latest version of POK-manager.sh.
For new setups or when recreating an instance:
`Run ./POK-manager.sh -create <instance_name>` or ` ./POK-manager.sh -edit.`
if you run `Run ./POK-manager.sh -create <instance_name>` You'll see a new option "Show Admin Commands In Chat" in the configuration process.
Set this to `TRUE` or `FALSE` as desired.
For existing setups: or using  `./POK-manager.sh -edit.`
If your Docker Compose file was generated before this update, you can manually add the following environment variable to your docker-compose-<instance_name>.yaml file:
```yaml
services:
  asaserver:
    environment:
      - SHOW_ADMIN_COMMANDS_IN_CHAT=FALSE 
 ```
After adding this, restart your server for the changes to take effect.
Alternatively, you can run ./POK-manager.sh -edit and select your instance to update its configuration, which will include this new option.
The -NotifyAdminCommandsInChat flag will now only be added to the server startup command when `SHOW_ADMIN_COMMANDS_IN_CHAT is set to TRUE.`
Thank you for your feedback! Let us know if you have any questions or if there's anything else we can help with.
