### ISSUE TITLE
Update build id could be wrong

### ISSUE THREAD

**Issue by locint** [Acekorneya/Ark-Survival-Ascended-Server#67]
Hello,

I was just checking https://steamdb.info/app/2430930/patchnotes/ and it's saying that the last build is 15752136 dated at 19. which matches perfectly with v52.28 - Minor version for Servers - 09/19/2024 but the update command claims that 15721846 is the latest build id. 

I guess https://api.steamcmd.net/v1/info/2430930 is not accurate anymore?

I did in fact a manual update and it downloaded some files but kept the old build id. WEIRD

Could be a rollback idk?

**Comment by Acekorneya** [comment]
yeah this was posted on their official ark discord 
```

dollie — Yesterday at 6:54 PM
Rollback to Previous version v52.27 - 09/19/2024

Temporary rollback of v52.28 due to issues with abnormal server lag on Aberration servers
```
