### ISSUE TITLE
It seems that the query port is not used anymore.

### ISSUE THREAD

**Issue by loginator** [Acekorneya/Ark-Survival-Ascended-Server#7]
Hey,
I've tried not forwarding the query port and the server works without any issues.
When having the query port forwarded I was not able to find the server using Steams server list.
So I guess the port is not used anymore.
Can anybody else confirm this and should it be removed from the dockerfile?

**Comment by Acekorneya** [comment]
Really?? Never tested that but yeah will test that maybe we don't need it I just have it as the other game used it

**Comment by Acekorneya** [comment]
Yes you are correct i've remove it as it was not needed
