### ISSUE TITLE
Unabke to start containers

### ISSUE THREAD

**Issue by james-barrett** [Acekorneya/Ark-Survival-Ascended-Server#70]
I've had the issue today where I got an error when trying to start the game containers.

The pok file was failing to set the variable docker_compose_command.

I manually set it to

docker compose 

and the servers successfully started, I don't have time to look deeper atm.

I could possibly be local to just my machine, needs looking at in more detail.

**Comment by Acekorneya** [comment]
maybe you updated docker compose to the plug-in version which uses docker compose compare to the older version which uses docker-compose but yeah it can be manually change in the file located in the config folder

**Comment by james-barrett** [comment]
I did nothing other than run apt update, apt upgrade so not sure what happened.
I'm due a reinstall soon so I will look at it again then.

**Comment by james-barrett** [comment]
Completely broken for me even on a clean install of Ubuntu server. I've even manually added "docker compose" to the cmd file, contains build but fail to run or respond to status.

Is it just me?

**Comment by Acekorneya** [comment]
What errors do you get??... like can you do the -logs command.... or what do you see in you console?? maybe i can see what is the issue..

**Comment by james-barrett** [comment]
Fresh install 
Docker version 27.3.1, build ce12230
Docker Compose version v2.29.7

fresh git clone
rename dir ark

./POK-manager.sh -create nameofserver

chose run without sudo as my user is in docker group

first output 

`Checking for updates to POK-manager.sh...
----- POK-manager.sh is already up to date -----
Using Docker Compose command: '' (read from file).
User james is already in the docker group.
Would you like to run Docker commands without 'sudo'? [y/N] y
Changing ownership of /var/run/docker.sock to james...
User preference saved. You can now run Docker commands without 'sudo'.
find: ‘./Instance_*’: No such file or directory
No existing instances found. Proceeding with default settings.
Current Configuration:

rest of settings
`

end of output with -f error

`Press Enter to accept the host default for the container timezone (Etc/UTC) or type to change: Europe/London
Configured Timezone: Europe/London
Would you like to review and edit the Docker Compose configuration before finalizing? [y/N]

Docker Compose configuration for SM_THE_ISLAND has been finalized.
Checking and adjusting ownership and permissions for /opt/server/ark/...
Ownership and permissions adjustment on /opt/server/ark/ completed.
-----Starting SM_THE_ISLAND Server-----
Using Docker Compose command: '' (read from file).
Using  for SM_THE_ISLAND...
2_0_latest: Pulling from acekorneya/asa_server
Digest: sha256:ab44d7a7e14c6e7efe0f27eecb84376da5397a9db59ae2adeb634aea89ccfd19
Status: Image is up to date for acekorneya/asa_server:2_0_latest
docker.io/acekorneya/asa_server:2_0_latest
./POK-manager.sh: line 1004: -f: command not found
2_0_latest: Pulling from acekorneya/asa_server
Digest: sha256:ab44d7a7e14c6e7efe0f27eecb84376da5397a9db59ae2adeb634aea89ccfd19
Status: Image is up to date for acekorneya/asa_server:2_0_latest
docker.io/acekorneya/asa_server:2_0_latest
-----Server Started for SM_THE_ISLAND -----
You can check the status of your server by running -status -all or -status SM_THE_ISLAND.
`

./POK-manager.sh -status -all

Checking for updates to POK-manager.sh...
----- POK-manager.sh is already up to date -----
Using Docker Compose command: '' (read from file).
User has chosen to run Docker commands without 'sudo'.
---- No Running Instances Found for command: -status -----
 To start an instance, use the -start -all or -start <instance_name> command.

./POK-manager.sh -create test - doesn't pull options from other instance i used as template

`Checking for updates to POK-manager.sh...
----- POK-manager.sh is already up to date -----
Using Docker Compose command: '' (read from file).
User has chosen to run Docker commands without 'sudo'.
Existing instances found. Would you like to copy settings from another instance? (y/N)
y
Select the instance you want to copy settings from:
1) SM_THE_ISLAND
#? 1
Copying settings from SM_THE_ISLAND...
./POK-manager.sh: line 602: yq: command not found
./POK-manager.sh: line 645: yq: command not found
Current Configuration:
Memory Limit: 
BattleEye: 
RCON Enabled: 
POK Monitor Message: 
Update Server: 
Update Interval: 
Update Window Start: 
Update Window End: 
Restart Notice: 
MOTD Enabled: 
MOTD: 
MOTD Duration: 
Map Name: 
Session Name: 
Admin Password: 
Server Password: 
ASA Port: 
RCON Port: 
Max Players: 
Show Admin Commands In Chat: 
Cluster ID: 
Mod IDs: 
Passive Mods: 
Custom Server Args: 
If you need to modify any setting, enter the setting name. Type 'confirm' to proceed with the current configuration.
Modify setting (or 'confirm'): 
`

i manually installed yq - same effect

cat config/POK-manager/docker_compose_cmd - empty file, i can add "docker compose" but your config checks for that?

any help appreciated.

**Comment by james-barrett** [comment]
Is it not this section?

If not cmd_file create file

then 

if cmd file

Docker Compose = cat cmd file

It will always be empty?

`
if [ ! -f "$cmd_file" ]; then
    touch "$cmd_file"
  fi
  if [ -f "$cmd_file" ]; then
    DOCKER_COMPOSE_CMD=$(cat "$cmd_file")
    echo "Using Docker Compose command: '$DOCKER_COMPOSE_CMD' (read from file)."

`

**Comment by james-barrett** [comment]
I changed the function below and now it create the config file correctly for me, just doing a test container

get_docker_compose_cmd() {
  local cmd_file="./config/POK-manager/docker_compose_cmd"
  local config_dir="./config/POK-manager"
  mkdir -p "$config_dir"

  if [ ! -f "$cmd_file" ]; then
    touch "$cmd_file"
  fi

  if [ -f "$cmd_file" ]; then
    DOCKER_COMPOSE_CMD=$(cat "$cmd_file")
    echo "Using Docker Compose command: '$DOCKER_COMPOSE_CMD' (read from file)."
  fi

  if [ -z "$DOCKER_COMPOSE_CMD" ]; then
    # Check for the Docker Compose V2 command availability ('docker compose')
    if docker compose version &>/dev/null; then
      DOCKER_COMPOSE_CMD="docker compose"
      echo $DOCKER_COMPOSE_CMD > $cmd_file
    elif docker-compose --version &>/dev/null; then
      # Fallback to Docker Compose V1 command if V2 is not available
      DOCKER_COMPOSE_CMD="docker-compose"
      echo $DOCKER_COMPOSE_CMD > $cmd_file
    else
      echo "Neither 'docker compose' (V2) nor 'docker-compose' (V1) command is available."
      echo "Please ensure Docker Compose is correctly installed."
      exit 1
    fi

    echo "Using Docker Compose command: '$DOCKER_COMPOSE_CMD'."
  fi
}

**Comment by james-barrett** [comment]
docker logs 

touch: cannot touch '/home/pok/arkserver/updating.flag': Permission denied
Current build ID is 15970310, initiating installation..
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.

**Comment by james-barrett** [comment]
----Starting Ark Server----

Error: Server files not found. Please ensure the server is properly installed.

**Comment by james-barrett** [comment]
Today after a clean git clone, manually adding the docker command to config file things seem to be running atm.

Will update after testing

**Comment by james-barrett** [comment]
Once i change the ports to suit my network I can no longer get info from -status command, also if I try to create and choose an existing version to copy from all the fields are blank. 

Assume these symptoms are part of the same issue.
