### ISSUE TITLE
Mod Maps

### ISSUE THREAD

**Issue by codekain** [Acekorneya/Ark-Survival-Ascended-Server#9]
i did edit the script to just use what ever i type in for the mapname but in the future will there be a way to just use -modmap=name and have it use what ever is entered. otherwise every time there is an update to the container will i have to just re edit the file...  just a thought i love the code other wise EZ to use my first time really playing with dockers tbh.

**Comment by codekain** [comment]
how about if the name is in brackets [ name_name_WP ] i just uses what ever is in-between

**Comment by Acekorneya** [comment]
I see what you mean yeah good idea I never though about the mod maps that people are starting to make... well this version which is still work in progress was to use the maps release by wild car but I never though about the mod maps so yeah I will add this to my todo list lol THANKS for the idea

**Comment by Acekorneya** [comment]
I've added a Way for user to add custom Map now so now you can just put Svartalfheim_WP as an example and it will work
